- src/schannel_cred.rs
... instead of threading through ownership. This matches builders in the
standard library like `Command`.
> Move the SChannelCred Builder to &mut self

- src/tls_stream.rs
Basic implementation to use the approximation returned by the crypto api,
to reduce the amount of API calls.
This essentially reads atleast the approximated amount of bytes.
> Read approximation on SEC_E_INCOMPLETE_MESSAGE

- src/lib.rs
Fixes #23. As mentioned in there, not sure if this is the behavior you want.
> Pass ISC_REQ_USE_SUPPLIED_CREDS to InitializeSecurityContext

- src/cert_chain.rs
- src/lib.rs
- src/test.rs
- src/tls_stream.rs
Openssl-inspired implementation of verification callbacks.
TODOs as of now:
When the related CertChainContext goes out of scope, CertChain points to invalid memory!
> Add a verification callback.

- src/cert_context.rs
This adds a similar interface to openssl's in regards to certificate fingerprinting.
Only SHA224 and RIPEMD160 are not supported since they aren't supported
by crypto32.
> Add more generic certificate fingerprinting API

- src/cert_chain.rs
- src/test.rs
- src/tls_stream.rs
This enables the workfow where an individual needs user confirmation for a failed certificate during verification callback.
> variant of verify_callback with additional context

- appveyor.yml
- src/test.rs
- src/tls_stream.rs
Fixes https://github.com/steffengy/schannel-rs/issues/34
I believe this is a solution which is both efficient by not discarding earlier encrypted bytes and correct by abiding the rules of the `Write` trait.
> Fix wrong Write implementation.

- src/schannel_cred.rs
Unsure if this breaks anything with client-certificates.
Not sure if they even work at this point.
I'd suggest landing this with potentially getting some feedback first
(if we can find someone that uses client certificates)
and then dealing with the fallout.
> do not automatically attempt to get a child-certificate chain, fix #37

- src/test.rs
- src/tls_stream.rs
cc @sfackler
Not sure this needs to ignore some kinds of errors?
Seems to atleast not break anything immediately, but I'm having
a feeling of missing something here.
Related to #34
> restore behavior to write_out without requiring an explicit flush

- src/cert_context.rs
PEM functionality is used by https://github.com/mcgoo/certstoretopem (which could just as well be an example added to this crate if you like.)
DER functionality will be used for https://github.com/alexcrichton/curl-rust/pull/185
cc @sfackler
> allow retrieving certs as pem or der and their valid use oids

- src/tls_stream.rs
If a renegotiation's been requested, we're responsible for the next
message, so we definitely don't need to read.
Closes #42
@gmbeard can you try out this branch to make sure it works as you'd expect?
> Fix handling of renegotiation requests

- src/cert_context.rs
- src/cert_store.rs
- src/test.rs
- src/tls_stream.rs
It looks like in order to support certificate chains longer than two certificates the `hAdditionalStore` parameter to `CertGetCertificateChain` needs to contain the certificate chain provided by the remote side, available through the `hCertStore` member of the certificate context (remarks on [QueryContextAttributes (General) function](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379326(v=vs.85).aspx)). See [Chromium cert_verify_proc_win.cc](https://chromium.googlesource.com/chromium/src/net/+/6a2d97ad76e85f195ec1edaf9dabbf08b9a8ab1d/cert/cert_verify_proc_win.cc#996).
I'm not sure I've done this correctly because I haven't used the schannel API directly before. This seems to work when the old code didn't.
Was there a reason for iteration of certificates in a store to require …
> support use of intermediate certificate authorities

- src/crypt_prov.rs
This PR is an initial implementation for importing a key into `ImportOptions`, and is required for [this PR](https://github.com/sfackler/rust-native-tls/issues/27) in `native-tls`.
> Add PKCS8 Key Import Support

- src/tls_stream.rs
It is not necessary for the underlying stream to be `Read + Write` for `get_ref`, `get_mut`, or `is_server`.
> Relax bounds for get_ref and get_mut

- src/cert_chain.rs
- src/lib.rs
- src/tls_stream.rs
Took a while, but here is an implementation providng access to the underlying handle values, which is decoupled from the winapi crate.
Pinging @Michael-F-Bryan @crusty-dave in case you're still interested in this.
References #58
> Provide access to underlying winapi values at initial set of places

- src/schannel_cred.rs
- src/security_context.rs
- src/test.rs
- src/tls_stream.rs
Adds an `Arc` within the `SchannelCred`, and slightly reworks the logic that uses it as a result. Not sure what to do about `get_mut()` at this point.
Added tests for the behavior by fetching the `SECPKG_ATTR_SESSION_INFO` attribute off the security context, which has information about whether the session was resumed.
Fixes #66.
> Allow the same SchannelCred to be used for multiple connections to support TLS session ticket resumption

- src/alpn_list.rs
- src/lib.rs
- src/security_context.rs
- src/test.rs
- src/tls_stream.rs
Implements both client and server-side ALPN negotiation support.
Note that this will only work in Windows 8.1 and above, not exactly sure what happens on Windows 7. https://github.com/curl/curl/issues/840 indicates that `QueryContextAttributes`, at least, will fail.
Adapted from #49.
> ALPN support

- src/schannel_cred.rs
While https://github.com/retep998/winapi-rs/issues/287 has not been resolved, it looks like `CALG_ECDH_EPHEM` was added in `winapi-rs` 0.3 with https://github.com/retep998/winapi-rs/commit/4bcd5e5ff04fc68a143fb1227eb9d7c97119bacc.
> Add EcdhEphem to the list of algorithms

- src/cert_store.rs
Wanted to make this a bit more type safe using an `enum` but after reading the MSDN docs it seems that the `pvPara` param is pretty "varied" depending on the context of other params. So as a small improvement just added the 2 other common locations to the docs.
> Added Slightly More Docs Regarding Common Trust Locations

- Cargo.toml
- appveyor.yml
- src/alpn_list.rs
- src/cert_chain.rs
- src/cert_context.rs
- src/cert_store.rs
- src/context_buffer.rs
- src/crypt_key.rs
- src/crypt_prov.rs
- src/ctl_context.rs
- src/lib.rs
- src/ncrypt_key.rs
- src/schannel_cred.rs
- src/security_context.rs
- src/test.rs
- src/tls_stream.rs
This PR resolves #75. Important bullet points:
* I have used `windows-sys` crate which is roughly equivalent to winapi. The higher-level `windows` crate doesn't currently work well with the functions returning HRESULT and suffers from occasional breaking changes in the APIs
* The MSRV is 1.40 due to added `non_exhaustive` pattern which replaces the manual one on several enums
* The code was formatted with rustfmt and updated to 2018 edition
* Fixed a few minor clippy warnings
* Tested with both -msvc and -gnu targets
* Mostly translates one to one with a few tweaks around mutability and types
> Switched from winapi to windows-rs

- appveyor.yml
I noticed in my other PR (#78) that the CI appears to use a very old rust version, even for nightly.
It turns out that Rust stopped providing .exe installers in 1.46.
This fixes the CI tests to use the latest nightly instead of nightly 1.46.
It also allows increasing the MSRV above 1.40, though this PR doesn't change it.
> Use MSI installation files for CI

- src/context_buffer.rs
In some situations, this crate may attempt to dereference a `ContextBuffer` as a `&[u8]` when the context buffer's underlying pointer is null. According to the docs for `slice::from_raw_parts`, this is undefined behavior, and leads to a crash in debug mode on my machine. To work around this, I've added a check for empty context buffers, which returns a constant empty slice instead. This seems to work correctly, but as I'm not familiar with this library, there may be some other invariant being violated. As such, I'm submitting this PR in the hopes that this solves the issue, or at least stimulates some discussion about the problem. Thanks!
> Prevent undefined behavior in context_buffer.rs

- Cargo.toml
- appveyor.yml
- src/ctl_context.rs
- src/lib.rs
- src/schannel_cred.rs
- src/test.rs
- src/tls_stream.rs
Uses a macro to null-terminate static strings at compile time.
This raises the MSRV of this crate to 1.46 due to the need for a loop in const-eval.
> Remove dependency on `lazy_static`

- Cargo.toml
- src/cert_context.rs
- src/cert_store.rs
- src/ctl_context.rs
- src/lib.rs
- src/schannel_cred.rs
- src/test.rs
- src/tls_stream.rs
Updated version of https://github.com/steffengy/schannel-rs/pull/89.
Release notes: https://github.com/microsoft/windows-rs/releases/tag/0.48.0
- `CRYPTOAPI_BLOB` renamed to `CRYPT_INTEGER_BLOB`: https://github.com/microsoft/win32metadata/commit/a35703057a1b2a8813154eca0acf1f4e5134a990
- `windows-sys-0.43` changed encoding for all string contants: https://github.com/microsoft/windows-rs/pull/2101
- `null_terminate!` removed as it's no longer needed.
- Use non-wide `UNISP_NAME_A`.
- All tests pass locally (with `SCHANNEL_RS_SKIP_SERVER_TESTS=1` as I don't want to install new certs on my machine).
> Bump windows-sys to 0.48.0

- src/cert_store.rs
Hi, I needed the exportable flag to be set and this seems to do the trick. It works on my machine (TM). I would appreciate it a lot if you would consider adding it to the library.
This is my first attempt of a PR. I hope I'm doing it correctly.
> Added function to set exportable private key flag

- .github/workflows/ci.yaml
- Cargo.toml
- src/schannel_cred.rs
- src/test.rs
- src/tls_stream.rs
CI only running for server 2022, which seems to support. Fix handling of reads of 2 SEC_E_OKs before first read going through.
Implements #104
> Add minimal TLS1.3 support on supported windows versions

- Cargo.toml
This reduces the size of the packaged crate (see the table below), and makes it easier to audit.
|              | before   | after    | percentage change |
|--------------|----------|----------|-------------------|
| uncompressed | 175.5KiB | 158.7KiB |             -9.6% |
| compressed   |  41.6KiB |  32.2KiB |            -22.6% |
Based on the downloads of the previous version, on average, this would reduce the total bandwidth for downloading this crate by 24.5GiB/month.
> Use `package.include` to only include necessary data for using the crate
